### ISSUE TITLE
Eclipse Neon Release

### ISSUE THREAD

**Issue by misto** [Cevelop/Issues#1]
Which plugins are ready for Neon?

* [x] CUTE
* [x] Mockator
* [x] Sconsolidator
* [x] Macronator
* [x] Elevator
* [x] Namespactor
* [x] Elevenator
* [x] CloneWar
* [x] Templator
* [x] Constificator
* [x] CharWars

We also need to update

* [x] Website
* [x] Arch Linux
* [x] Brew

**Comment by tcorbat** [comment]
Plug-ins are looking good. Tests are green. Let's create a release candidate for further testing!

**Comment by tcorbat** [comment]
Patched CDT with const placement fix created.

**Comment by misto** [comment]
New builds are available on c202.hsr.ch/ifsproj/Cevelop, please test one and check below:
- [x] Windows 
- [x] OSX
- [x] Linux

**Comment by misto** [comment]
Website has been updated, see the preview here: http://sifsv-80033.hsr.ch/ (internal only)

**Comment by tonisuter** [comment]
I tested the OSX version and everything seems to work. The website looks good too!

**Comment by misto** [comment]
Released!
