### ISSUE TITLE
how to get rid off "Un- or ill-initialized variable" 

### ISSUE THREAD

**Issue by testalucida** [Cevelop/Issues#119]
I'm using Cevelop version 1.13.0-201910070714. OS Ubuntu 18.04.
Whenever I'm defining a variable "the old way", let's say
int i = 0;
a green circle with a white star in it appears to the left and complains "Un- or ill-initialized variable".
That is because the IDE wants me defining the variable "the new way",
int i {0};
Neither do I want this curly bracket initialization nor do I like the alternative beside each and every variable definition: a comment like // @suppress("Un- or ill-initialized variables") which makes the green circle disappear.

AFAIK, in older versions of Cevelop one could switch off this option globally in Preferences/C++/Code Analysis.
Unfortunately, this option doesn't seem to live there anymore.
I tried switching compile option -std from c++1z to c++11 but without success.
Can anyone tell me where I can find this global option now?

Thanks in advance!

**Comment by tcorbat** [comment]
Hi

There are preferences which are workspace-wide and there are project properties which are configured per project. The Elevenator plug-in configures projects with default settings. They activate the Elevator plug-in that contains this checker by default. Please check the properties of your project (C/C++ General -> Code Analysis -> C++11 Code Enhancements -> Un- or ill-initialized variables).

Later today we are planning to release Cevelop 1.14.0, which contains an updated version of the Elevator plug-in. The "Un- or ill-initialized variables" checker will then not report declarations with equals-initializer.

I hope this helps.
Thomas

**Comment by testalucida** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-size:14px;font-family:verdana, geneva, sans-serif;;}Hi Thomas,thanks for your reply.Switching from "use workspace settings" to "use project settings" solved my problem.Have a nice dayMartin
tcorbat schrieb am 17.02.2020 08:57 (GMT +01:00):

Hi
There are preferences which are workspace-wide and there are project properties which are configured per project. The Elevenator plug-in configures projects with default settings. They activate the Elevator plug-in that contains this checker by default. Please check the properties of your project (C/C++ General -> Code Analysis -> C++11 Code Enhancements -> Un- or ill-initialized variables).
Later today we are planning to release Cevelop 1.14.0, which contains an updated version of the Elevator plug-in. The "Un- or ill-initialized variables" checker will then not report declarations with equals-initializer.
I hope this helps.Thomas
