### ISSUE TITLE
Error trying to run Linticator in MCUXpresso

### ISSUE THREAD

**Issue by scottdwhitney** [Cevelop/Issues#129]
### Expected Behavior

Installed Linticator plugin for Eclipse in MCUXpresso and pointed to my PC-Lint Plus installation, adding executable C:\PCLP\windows\pclp64.exe, compiler configuration C:\PCLP\windows\config\MCU\co-arm-none-eabi-gcc.lnt, and header configuration file C:\PCLP\windows\config\MCU\co-arm-none-eabi-gcc.h.  

Ran Linticator Test Configuration and got the following:
![image](https://user-images.githubusercontent.com/67105248/188172589-c8c9f058-6e8e-428d-ac65-6162db063e37.png)

Enabled Linticator for my project.  Then right clicked and selected Linticator/Run Linticator on project.  Expected PC-Lint Plus to be run.

### Actual Behavior

Immediately got an error dialog:
![image](https://user-images.githubusercontent.com/67105248/188171723-e5d805a7-a503-4f36-a58f-a0f2ee257dc0.png)

### Cevelop Version, Operating System and Compiler

Running Windows 11 and MCUXpresso 11.6.0.  Any suggestions on what am I doing wrong?

**Comment by misto** [comment]
Dear Scott, thanks for reporting this. That NullPointerException doesn't sound good, could you maybe check the error log to see if there's a stack trace that would help us locate the error? You should find it under Window -> Show view -> Other. Then select General > Error Log.

**Comment by scottdwhitney** [comment]
Hi Mirko,

I have attached the requested Error Log.  Please let me know what else I can try.

Best regards,

Scott

**Comment by misto** [comment]
Sorry, that didn't come through here..

**Comment by scottdwhitney** [comment]
Sorry, I guess replying to the e-mail did not work as expected.  I have attached the requested Error Log.  Please let me know what else I can try.
[MCUXpresso Linticator General Error Log.log](https://github.com/Cevelop/Issues/files/9500385/MCUXpresso.Linticator.General.Error.Log.log)

**Comment by scottdwhitney** [comment]
I noticed this morning that when I tried to check Linticator/Configure Linticator.../License, I got the following error message:

![image](https://user-images.githubusercontent.com/67105248/188877613-b010cb5b-17d5-4ce5-8199-642648b38efb.png)
I am not sure if this is related to the error that I am seeing.

**Comment by scottdwhitney** [comment]
Is it possible that there are problems due to trying to run Linticator in a directory that contains spaces, such as on OneDrive?  For example, The path to a given file might be C:\Users\swhitney\OneDrive - Company Name\Project Name\repository-name.  Thanks for any insight - I'd really like to get Linticator to work for me.

**Comment by scottdwhitney** [comment]
I have not heard anything back for nearly two weeks.  Do you have any suggestions on what I can try to get Linticator working, or should I just give up on it?  Thanks for your advice.

**Comment by misto** [comment]
I'm sorry, I haven't yet been able to reproduce this..  the spaces (and OneDrive) might cause this, but sometimes the IDE also changes some underlying things from the official Eclipse version, so it's often difficult to pinpoint such errors.

**Comment by scottdwhitney** [comment]
That's a shame. I think I will have to give up on using Linticator for our project.  Thank you for responding and best wishes.
