### ISSUE TITLE
Download links to binaries on website do not work

### ISSUE THREAD

**Issue by dhebbeker** [Cevelop/Issues#132]
The download links on [the website](https://www.cevelop.com/download/) to the binaries are broken (for all OS).

**Comment by Audifire** [comment]
Fixed in https://github.com/Cevelop/cevelop.github.io/commit/656265b468deb0dba2714d48be8b3fdb503d6d0a

**Comment by dhebbeker** [comment]
OK, now the link works, but the archive is only 135 bytes large. The file pointed to is definitively not the correct or complete binary.

**Comment by Audifire** [comment]
Should be finally fixed now. Let me know, if something is not working properly.
