### ISSUE TITLE
Updates Licenses

### ISSUE THREAD

**Issue by misto** [Cevelop/Issues#18]
We need to go through all our plug-ins and check their licenses (and update to the Cevelop license if needed).

**Comment by fmorgner** [comment]
Fixed for com.cevelop.plugins

**Comment by Darnor** [comment]
Updated the licence for:
- CUTE (except CUTE Boost which uses the Boost 1.0 Licence)
- Cevelop Plug-ins
- ILTIS
- SConsolidator
- Linticator has already been updated
