### ISSUE TITLE
toggle function definition refactoring should also toggle =default definitions

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#2]
### Expected Behavior

Special member functions can be user-defined with =default or user-declared as =delete. A user-defined special member function can be user-declared within a class' body, but declared outside, so the toggle function body refactoring should treat =default like a normal function body.

### Actual Behavior

toggle function definition does not work on user-declared and user-defined with =default class members

### Cevelop Version, Operating System and Compiler

all before Neon

**Comment by misto** [comment]
Thank you for taking the time to report this issue! Unfortunately, this isn't really a bug in Cevelop, but you should consider reporting it to the [Eclipse CDT issue tracker](https://bugs.eclipse.org/bugs/) instead.

**Comment by PeterSommerlad** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=496927
