### ISSUE TITLE
Web Site Beta Plugin page should list available plugins

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#21]
### Expected Behavior

A short description of available beta features may be including upcoming ones should be listed

### Actual Behavior

Only the screenshot shows potentially  available plugins without giving an idea what they are for

### Cevelop Version, Operating System and Compiler

N/a. Website

**Comment by tonisuter** [comment]
I added a short description of the three beta plug-ins (Constificator, GSLAtor, Intwidthfixator) to the [Beta Plug-ins page](https://www.cevelop.com/beta/).
