### ISSUE TITLE
CMake Support?

### ISSUE THREAD

**Issue by tgharib** [Cevelop/Issues#23]
### Expected Behavior

The IDE to be able to create projects based on CMake project files or at least for the IDE to parse CMake project files.

### Actual Behavior

There doesn't seem to be any option to create or import a CMake project.

### Cevelop Version, Operating System and Compiler

Version 1.6 on Manjaro Linux with GCC 6.3.1.

I found out about this project recently and I'm interested in using this IDE so I was wondering if cmake support is on the plan.

**Comment by tcorbat** [comment]
Currently we don't support CMake based projects. There is an open issue in CDT regarding this topic [1]. We will adopt that feature when it is implemented. Until then you can configure build targets for your CMake project manually. There is a tutorial that should work for Cevelop as well [2].


[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=174176
[2] http://sgpsproject.sourceforge.net/JavierVGomez/index.php/How_to_configure_a_C/C%2B%2B_project_with_Eclipse_and_CMake

**Comment by tgharib** [comment]
Thank you for the helpful links. Would you prefer if I close this issue or leave it open?

**Comment by tcorbat** [comment]
You're welcome. I didn't close the ticket yet, as I wanted to know whether the suggested workarounds are useful. We will adopt CDTs CMake support anyway. Thus I'll close the ticket.
