### ISSUE TITLE
open refactor menu (with beta plugins installed) gives BBOD (hangs) on os x

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#24]
### Expected Behavior

Opening the context menu with refactor selected, should work
### Actual Behavior

I got the "BBOD" beach-ball of death on mac os and Cevelop hangs

### Cevelop Version, Operating System and Compiler

1.7.0. downloaded fresh with all beta plugins installed
almost empty cute project.

**Comment by PeterSommerlad** [comment]
![screen shot 2017-04-20 at 14 56 41](https://cloud.githubusercontent.com/assets/1725845/25231934/facec696-25d9-11e7-8253-ebd4dd3c25dd.png)

**Comment by PeterSommerlad** [comment]
It seems the culprit is the Intwitdthfixator! without it it is not reproducible and its the only one that actually puts something into the refactoring menu. I suspect the code for checking if it is to go into the menu has a problem, or the menu entry xml is somehow broken.

**Comment by PeterSommerlad** [comment]
Toni had the same effect! So it is not my mac only

**Comment by tcorbat** [comment]
Fixed in the latest build of the plug-in. It should be fixed if you update IntWidthFixator now.
