### ISSUE TITLE
Some Editor Text not visible in Dark Theme

### ISSUE THREAD

**Issue by motowizlee** [Cevelop/Issues#26]
### Expected Behavior

- Expected will be able to see the text clearly as with other part of the code. Seems like the region of code that are not clear is only in the `#if #endif` block and the currently selected word (which in the screenshot below is the word "`U_EXPORT2`" in the middle of the picture). 

- Most probably this can be changed in the Color and Font preference but wasn't sure in which section to change. Was expecting the preference to be in the line of "inactive preprocessor" or "inactive code region" etc.

### Actual Behavior
**without highlighting the text**
![image](https://cloud.githubusercontent.com/assets/27324034/25470447/c8a7f90a-2b54-11e7-9cec-e93d93e97b1c.png)

**when text highlighted**
![image](https://cloud.githubusercontent.com/assets/27324034/25470471/e21771a4-2b54-11e7-8739-f798ee1ed845.png)

### Cevelop Version, Operating System and Compiler

- Cevelop C++ IDE Version: 1.7.1-201704211123 (64-bit version)
- Windows 10 Pro 64-bit
- Theme: Dark
- Color and Font theme: Default (current)
- Checked "Use mixed fonts and colors for labels" and "Show most recently used tabs" options 

By the way, thanks for the great piece of software! This is by far the best free IDE for C/C++ so far after trying basically all the free C/C++ IDE.

**Comment by fmorgner** [comment]
Hi @motowizlee, first of all thanks for taking the time to report the issue and thank you for your kind words!

Sadly the 'Dark Theme' has some issues, but you can change the background of inactive code the following way:

1. Open the preferences
2. Navigate to "C/C++ -> Editor"
3. In the "Editor" Preference pane there is a section called "Appearance color options".
4. Select "Inactive code highlight" from the associated list
5. Select a different color via the color picker on the side of the list.

![color-settings](https://cloud.githubusercontent.com/assets/196091/25739771/a1cb92b2-3183-11e7-8e0c-33471157dca0.png)

Thanks again for helping us to improve Cevelop by reporting problems!

**Comment by motowizlee** [comment]
Thanks @fmorgner for the solution! That solves the issue.

**Comment by motowizlee** [comment]
@fmorgner thanks to your tip, I also manage to solve some other more minor issue with the dark theme for example with setting such as the annotation with "C++ occurrence" and "C++ write occurrence", and also the "View and Editor Folders" in "General->Appearance->Colors and Fonts". Attach with this is the preference that I exported in hope that it can help to make this editor better.

Thanks.

[preference.zip](https://github.com/Cevelop/Issues/files/995847/preference.zip)
