### ISSUE TITLE
Problems with getting beta plugins

### ISSUE THREAD

**Issue by armarkos** [Cevelop/Issues#28]
Hi folks,

I am trying to install beta plugins. When I specify the path: https://www.cevelop.com/update/1.7.0 it shows and error. Here is the log:

```
Unable to read repository at https://www.cevelop.com/update/1.7.0/content.xml.
Unable to read repository at https://www.cevelop.com/update/1.7.0/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Do you know what is going on?

Thanks,
Aram

**Comment by fmorgner** [comment]
It looks like your Java installation is unable to verify the TLS certificate we use for cevelop.com. Can you access the URL via your web browser? What operating system are you using? If you are able to access the URL using your regular web browser, maybe your Java Trust Store is not in sync with your system certificate store.

**Comment by misto** [comment]
I'm closing this for now, please reopen if there's anything we can do.
