### ISSUE TITLE
Cevelop doesn't ship with Cute headers ( No Puns not intended )

### ISSUE THREAD

**Issue by codecnotsupported** [Cevelop/Issues#29]
### Expected Behavior
Include cute headers without issues.

### Actual Behavior

Can't find cute headers

### Cevelop Version, Operating System and Compiler

Cevelop 1.7.1 with beta plugins. On Linux 4.10.0-21-generic. gcc version 7.0.1 20170407

### Temporary fix: 
Reinstall Cute.

**Comment by fmorgner** [comment]
How did you create your Project? Cevelop provides the CUTE headers when creating a new CUTE Project.

**Comment by codecnotsupported** [comment]
There wasn't a option to create a CUTE project, only a cute suite. 

But to make sure I shall do a clean install and recheck. [ ]

**Comment by PeterSommerlad** [comment]
Try: File-->New C++ Project -> Wizard opens
select first folder CUTE -> CUTE project


Sorry for the confusion. We might make a CUTE project entry more prominent in the top-level menu in a future release.

**Comment by codecnotsupported** [comment]
I just rechecked, it did seem to be a problem with my specific configuration. ( I just ran a fresh install )
Also @PeterSommerlad, in my honest opinion it's not confusing. But somehow I managed to remove the cute project preset.

Also thanks for your input @fmorgner, @PeterSommerlad.
