### ISSUE TITLE
constificator decltype(auto) problen

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#30]
### Expected Behavior

constificator should add only one const to decltype(auto) and then be silent

### Actual Behavior

even after automatically adding const, constificator insists on adding auto again on decltype(auto) const , chosing to do so , changes nothing 

### Cevelop Version, Operating System and Compiler

current release 1.7

**Comment by PeterSommerlad** [comment]
or constificator doesn't add const at all.

**Comment by misto** [comment]
@fmorgner @tcorbat is this still a problem with 1.8?

**Comment by Darnor** [comment]
Constificator will no longer suggest adding const to a decltype(auto) since this is not valid according to the standard, even though some compilers will still compile it (e.g. gcc).
