### ISSUE TITLE
Refactor from C-array to std::array Loses Initializers

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#33]
Starting with:

`string status_text[] {
    "Rel", "Att", "Att", "Low", "Std", "Fre"
};`

the refactor to std::array results in:

`std::array<string, 6> status_text;
`

so the initialization is lost. Also, had to change to an explicit subscript declaration for this to work but that's due to the nature of std::array.

Cevelop 1.7.1
GCC 4.9
Ubuntu 14.04.5

**Comment by tcorbat** [comment]
Thanks for reporting this issue! I was able to reproduce it. We'll try to fix this for the next release.

**Comment by tonisuter** [comment]
Thanks for the bug report! This issue is now fixed on the master branch and the fix will be part of the next Cevelop release.
