### ISSUE TITLE
Constructor Order of Initialization Gives False Warning

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#38]
The following class and constructor receive the warning about initializing members should be in the proper order:

```
class test {
public:
    test(const uint16_t x, const uint16_t y) :
        x { x }, y { x } {
    }

    uint16_t z { };
    uint16_t x;
    uint16_t y;
};

```
The actual order is okay but the detector doesn't like 'z' being initialized at its declaration. Only with 'z' in the constructor initialization list is the detector satisfied.

**Comment by tcorbat** [comment]
Confirmed, that's a bug in the core guideline checker for C47.

**Comment by Darnor** [comment]
This is resolved in recent versions of the GSLAtor plug-in.
