### ISSUE TITLE
Warning to create namespace swap fails with template classes

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#39]
Trying to create a simple example for another issue I ran into the suggestion to create swap functions for a template class. After creating the namespace swap function it is not recognized and the warning continues. 

```
#include <vector>
#include <utility>

template <typename T>
struct A {
    std::vector<T> mValues { };

    void swap(A& other) noexcept {
        using std::swap;
    }
};

template <typename T>
void swap(A<T>& a, A<T>& b) noexcept {
    a.swap(b);
}

```
I let the "quick fix" create both swaps. The namespace swap was generated as a regular function. I changed it to being a template.

**Comment by tcorbat** [comment]
Thanks for the report, we will look into it. It s probably a glitch that
templates are not handled correctly.
By the way, it is great you are reporting all those issues!

**Comment by rmerriam** [comment]
I've 9,000 lines of code from a recent project that I'm running through the process. 

There are a number of the refactoring capabilities I don't understand. Is there more detailed documentation somewhere? I don't see it on the web site, at least.

**Comment by tonisuter** [comment]
Unfortunately, the user guides of the various refactoring plug-ins are spread across various websites: 

* Macronator - Remove macros from C++ code
See http://cute-test.com/projects/macronator/wiki

* Namespactor - Various namespace / typealias refactorings
See http://cute-test.com/projects/cute/wiki/Namespactor

* Includator - Manage include dependencies in C++ projects
See http://includator.com

* Constificator - Helps to write const-correct code (Note that this is currently a [beta plug-in](https://www.cevelop.com/beta/))
See https://www.cevelop.com/resources/Constificator_Documentation.pdf

I hope this helps.

**Comment by tcorbat** [comment]
We've fixed the creation of the namespace level swap function for templates. The quick fix should now make swap a template too and and the required template parameters.
