### ISSUE TITLE
Questionable ES.26: Dont use a variable for two unrelated purposes

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#41]
The following class embedded in another class get the E.26 warning on the --mDepth in the destructor.

```
        struct Depth {
            Depth() noexcept {
                ++mDepth;
            }
            ~Depth() noexcept {
                --mDepth;   // E.26
            }
            static int8_t mDepth { };
        };

```
Don't understand why this is produces a warning.

In another location this code generates the same warning:

```
const string TreeNode::getNodeText() const {
    string text = getNodeId() + " ";
    text += getName() + " ";
    text += getStateText(mState) + " ";
    return text;
}

```
The second example is a standard approach to building up a string so is misleading. But I can understand why the warning is produced.

**Comment by tcorbat** [comment]
I agree, the current implementation of this Core Guideline Check is
probably confusing and does not reflect the intention of the rule. Only
local variables and multiple direct assignments should be reported.

**Comment by rmerriam** [comment]
The Depth class is also getting the warning:`C.45: In-class member variables should be default initialized`

It's a trick class because it wraps a counter used for indenting text output. The constructor and destructor change the indent level. 

`
cout << setw(mDepth*2) << x;
`

**Comment by tcorbat** [comment]
We have fixed both issues (ES.26 & C.45). The fixes will be available in the Oxygen release of Cevelop - version 1.8.0.
