### ISSUE TITLE
cute-test plugin misses namespace qualification from tests within a namespace

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#46]
### Expected Behavior

A test function in a named non-inline namespace is marked by the codan checker, when added by the quick-fix the test name should be qualified with the namespace.

### Actual Behavior

qualification is missing. compile error.

### Cevelop Version, Operating System and Compiler

current, as of today: Version: 1.8.0-201707131430

**Comment by PeterSommerlad** [comment]
In addition, after manually adding the namespace qualifier to the test insertions, the checker does not recognize them as registered any more. in general test case detection and insertion seems to be deficient with namespaces involved. Such namespaces come in handy, when duplicating tests with different implementation (details)

**Comment by Darnor** [comment]
This has been fixed in the latest versions of the CUTE plug-in.
