### ISSUE TITLE
Constificator suggests to add const on a function parameter having an alias type for a const qualified type

### ISSUE THREAD

**Issue by fmorgner** [Cevelop/Issues#55]
### Expected Behavior

Constificator should not suggest adding const to `foo` in the following example.

```c++
using alias = int const;

void funct(alias foo) {
}
```

### Actual Behavior

Constificator suggest adding const-qualification to `foo`.

### Cevelop Version, Operating System and Compiler

Current release and current master. OS and Compiler not applicable

**Comment by Darnor** [comment]
Fixed in latest Constificator update.
