### ISSUE TITLE
Constificator Marks Reference Type of Constructor Argument

### ISSUE THREAD

**Issue by tcorbat** [Cevelop/Issues#56]
### Expected Behavior

void printSomething(std::ostream & o) { //constificator should not report "std::ostream & o" to be constable
	std::ostream_iterator<int> out{o, "\n"};
	//...
}

### Actual Behavior

Parameter o is reported to be constable

### Cevelop Version, Operating System and Compiler

Cevelop 1.8.0

**Comment by fmorgner** [comment]
Fixed upstream.
