### ISSUE TITLE
Plugin provider names are inconsistent

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#60]
### Expected Behavior

all Cevelop and IFS plug-ins should have the same plug-in provider name, so that sorting in "Installation Details" by provider name groups them together

the name should be "IFS Institute for Software"

### Actual Behavior

we have plug-ins with the provider names

- IFS
- IFS Institute for Software
- Institute for Software
- Michael Rüegg

### Cevelop Version, Operating System and Compiler

N/A, current Cevelop on Mac

**Comment by Darnor** [comment]
Providor Updates have been updated except for two plugins:
- Mockator will update after "iltisation" is done
- Cevelop Branding will update after the next Cevelop release
