### ISSUE TITLE
Can not update beta plugins, because Intwidthfixator already relies on ILTIS

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#61]
### Expected Behavior

update installed Cevelop beta plug-ins should continue to work

### Actual Behavior

Error message:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Intwidthfixator 1.8.0.201711052338 (com.cevelop.intwidthfixator.feature.feature.group 1.8.0.201711052338)
  Missing requirement: Intwidthfixator 1.8.0.201711052338 (com.cevelop.intwidthfixator 1.8.0.201711052338) requires 'bundle ch.hsr.ifs.iltis.cpp 0.1.0' but it could not be found
  Cannot satisfy dependency:
    From: Intwidthfixator 1.8.0.201711052338 (com.cevelop.intwidthfixator.feature.feature.group 1.8.0.201711052338)
    To: com.cevelop.intwidthfixator [1.8.0.201711052338]

workaround, deselect IntWidthfixator then I could update.

### Cevelop Version, Operating System and Compiler

The more we know about your setup, the easier it will be for us to reproduce the problem.

**Comment by Darnor** [comment]
Should be fixed with the newest Intwidthfixator update.
