### ISSUE TITLE
variable initialization checker wants to add curly braces to catch clause

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#62]
### Expected Behavior

```catch(const int) {}```

should not be marked as missing initialization

### Actual Behavior

white star on green marker wants to add {} and the quick fix does:

```catch (const int {})```

which is a compile error 

### Cevelop Version, Operating System and Compiler

current updated plugins (Cevelop 1.8)

**Comment by Darnor** [comment]
Fixed with the next Elevator update.
