### ISSUE TITLE
CStylechecker checks for endl in the Missing standard include checker

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#63]
### Expected Behavior

want to individually allow std::endl usage.

### Actual Behavior

S marker complains, but can not opt out of the check. From twiddling with the Codan properties 
i found that "Missing Standard Include" is turning it off.

### Cevelop Version, Operating System and Compiler

recent as of today.

**Comment by PeterSommerlad** [comment]
oh, it was complaining the missing header really, not the use of endl.

**Comment by tcorbat** [comment]
That's an issue that we could look into when stream includes are improved
in general, as an extra ostream include wasn't necessary if you had other
stream includes, like iostream.
