### ISSUE TITLE
Add Oxygen Update Site

### ISSUE THREAD

**Issue by Darnor** [Cevelop/Issues#71]
If someone wants to install DevStyle the Oxygen update site needs to be added manually.

Since this plug-in is very popular it would be great to make things easier, be providing the update site per default.

See also comments about problems with installing other plug-ins here: https://www.reddit.com/r/cpp/comments/7x3wp0/cevelop_190_oxygen2_release/

**Comment by tcorbat** [comment]
That's correct. If I recall correctly we refrained from adding any other update-site apart from out beta plug-ins, as Cevelop tries to update core components of itself, which it is not able to an fails. We are currently discussing whether we should bundle DevStyle with Cevelop. But this would only circumvent this specifc case, other plug-ins might have the same issue. We'll check other implications and might eventually add the Oxygen updatesite by default.

**Comment by stayprivates** [comment]
I'm voting for that  feature ;-)  This might allow you guys to iron out some issue, that might be related to compability with Cevelop and DarkestTheme. When that plug-in is installed I'm getting alot more error in the log file. Might be generic Eclipse/Darkest Theme or specific to Cevelop I don't know.

**Comment by Darnor** [comment]
Eclipse update-sites are now added by default (release 1.12.0+).
