### ISSUE TITLE
Wrong const suggestion from constificator

### ISSUE THREAD

**Issue by morgner** [Cevelop/Issues#79]
### Expected Behavior

No hint to make function parameter _TMapL2L & m_ const

### Actual Behavior

Hint to make function parameter _TMapL2L & m_ const

### Cevelop Version, Operating System and Compiler

Cevelop C++ IDE
Version: 1.9.1-201802220948

OS: Linux, v.4.16.5-300.fc28.x86_64, x86_64 / gtk 2.24.32

[non-const-map.zip](https://github.com/Cevelop/Issues/files/1976545/non-const-map.zip)

### The code
```cpp
#include <map>

using TMapL2L = std::map<long, long>;

long doit(TMapL2L & m)
  {
  return m[3];
  }

int main()
  {
  TMapL2L lm{ {1, 2} };
  doit(lm);
  }
```

**Comment by fmorgner** [comment]
Thanks for reporting! The bug has been fixed on `develop`. The fix will be included in next release.
