### ISSUE TITLE
ES.20 false positive on range for variable

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#81]
### Expected Behavior

```
		for(auto &drawable:content){
			drawable->draw(out);
		}
```
should be OK
### Actual Behavior

on for line I get ES.20 triggered
![screen shot 2018-05-24 at 15 14 12](https://user-images.githubusercontent.com/1725845/40487729-57c8db32-5f65-11e8-962b-8641b9d7f7c3.png)

applying quick fix makes code incorrect:

```
	for(auto &drawable {}:content) {
			drawable->draw(out);
		}

```

### Cevelop Version, Operating System and Compiler

current

**Comment by tcorbat** [comment]
Fixed. Will be available as soon as Jenkins can communicate with our repository again.
