### ISSUE TITLE
Roadmap: Update to Eclipse Photon / CDT 9.5?

### ISSUE THREAD

**Issue by dermojo** [Cevelop/Issues#82]
Hi there,
With the most recent Eclipse/CDT release, multiple enhancements have been made to (finally) support more C++14 and C++17 features.
I was wondering what Cevelop's roadmap is and if/when a release based on the new CDT would be possible?
Thanks!

**Comment by fmorgner** [comment]
Thanks for your request, we are currently working on Cevelop based on CDT 9.5.1. We are aiming towards a release at the end of the week.

**Comment by dermojo** [comment]
Great to hear, looking forward to it!
Thanks.
