### ISSUE TITLE
Update to CDT 9.6

### ISSUE THREAD

**Issue by dermojo** [Cevelop/Issues#85]
Hi!
CDT 9.6 fixes a few indexer problems I'm having with GCC 8 and type_traits.
Are there any plans to upgrade in  the near future?
Thanks!

**Comment by tcorbat** [comment]
Dear Daniel

We are currently in the finalization step to ensure compatibility of our
plug-ins with CDT 9.6. As soon as this is comoleted we will release a new
Cevelop version based on it. You can expect this to happen within the next
two weeks.

Best Regards
Thomas

**Comment by dermojo** [comment]
Great, thanks!

**Comment by dermojo** [comment]
Closed with the current release.
By the way: Is there a way to be notified about planned releases etc., so I can look up when the next release is planned instead of opening an issue?

**Comment by tonisuter** [comment]
Hi Daniel

While we don't have a fixed release schedule, we usually release a new version of Cevelop soon after a new version of Eclipse CDT ships. Sometimes, if necessary, we also ship bugfix releases in between. For example, Eclipse CDT 9.7.0 is currently planned for March 20th, 2019 (see https://projects.eclipse.org/projects/tools.cdt). We plan to release Cevelop 1.12.0 soon after that.

To get notified about new releases of Cevelop you can either follow the [@cevelop](https://twitter.com/cevelop) account on Twitter or subscribe to our [RSS feed](https://www.cevelop.com/feed.xml).

Best regards
Toni

**Comment by dermojo** [comment]
Good to know, thanks a lot!
