### ISSUE TITLE
Cevelop Plug-ins Beta Channel

### ISSUE THREAD

**Issue by misto** [Cevelop/Issues#9]
Add an update site to install beta plug-ins (int-width-fixator, core-guidelines checker). Add this update site to Cevelop and place it on the website.

**Comment by fmorgner** [comment]
The update site is in place.

**Comment by misto** [comment]
During the installation, I noticed that both plug-ins are licensed under the EPL. Is that really our intention? @PeterSommerlad

**Comment by PeterSommerlad** [comment]
No

**Comment by fmorgner** [comment]
Closing since the Beta channel for the current release is available via: https://www.cevelop.com/update/1.7.0
