### ISSUE TITLE
Cevelop download on Windows 10 does not start out of the box

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#91]
### Expected Behavior

After downloading Cevelop on a vanilla Windows 10 VM should just work

### Actual Behavior

starting Cevelop one gets complains "The Cevelop executable launcher was unable to find its companion shared library"
 
### Cevelop Version, Operating System and Compiler

current download release 1.11.1 Windows 10 VM on Parallels for Mac

**Comment by PeterSommerlad** [comment]
should become a FAQ entry, that Java must be installed on Windows also and the 64 bit version!

**Comment by PeterSommerlad** [comment]
falscher button

**Comment by tonisuter** [comment]
Ok, I added an [FAQ](https://cevelop.com/faq/) entry.
