### ISSUE TITLE
TDD create member function puts function in global scope

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#96]
### Expected Behavior

```
struct Switch {
};
void testSwitchZero(){
	Switch const s { };
	bool res=s.isOff(); // quick-fix
	ASSERTM(res,"default constructed Switch is off");
}
```

should result in

``` 
struct Switch {
    bool isOff() const { return bool();}
};
```

### Actual Behavior

```
bool isOff() const {
	return bool();
}
```

is inserted at the end of the file

### Cevelop Version, Operating System and Compiler

Cevelop C++ IDE

Version: 1.11.1-201904151432

and 
Cevelop C++ IDE

Version: 1.11.1-201902151304

**Comment by Darnor** [comment]
Will be fixed with the next release. Thank you for reporting this issue.
